name: Subgraph testnets deployment

on:
  push:
    paths:
    - 'packages/subgraph/**'
    branches:
    - 'development'

env:
  GRAPHKEY: ${{secrets.GRAPHKEY}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: yarn --frozen-lockfile
    - name: Authenticate
      run: .github/scripts/kubectl-config.sh ${{secrets.KUBE_CA}} ${{secrets.KUBE_SERVER}} ${{secrets.KUBE_TOKEN}}
    - name: Rinkeby
      run: yarn workspace @aragon/court-subgraph deploy:rinkeby
    - name: Staging
      run: yarn workspace @aragon/court-subgraph deploy:staging