name: Subgraph mainnet deployment

on:
  push:
    paths:
    - 'packages/subgraph/**'
    branches:
    - 'master'

env:
  GRAPHKEY: ${{secrets.GRAPHKEY}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: yarn --frozen-lockfile
    - name: Authenticate
      run: .github/scripts/kubectl-config.sh ${{secrets.KUBE_CA}} ${{secrets.KUBE_SERVER}} ${{secrets.KUBE_TOKEN}}
    - name: Deploy
      run: yarn workspace @aragon/court-subgraph deploy:mainnet
